### ISSUE TITLE
User Story 7 -  Task Overview

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#16]
## Value proposition
As a **team member**
I want to **see a list of tasks**
In order to **to have an overview of the project**
## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/51b9bef0-f4e8-475c-b9df-9a6b0e809aea)

## Acceptance criteria
- [ ] Task List is displayed in the Project Detail Page below the Project Title
- [ ] Each Task is shown as a list item with task’s title
- [ ] An appropriate loading and error messages will be displayed in corresponding situations
## Tasks
- [ ] create a new collection in MongoDB named Tasks
- [ ] create a new model in db/models named Task for a schema for tasks
- [ ] import Model in pages/api /tasks/ index
- [ ] use GET method to fetch data from db and implement error handling
- [ ] create a TaskList component as an ul, props : 
   - [ ] {tasks}
   - [ ] map over tasks and for each render Task component
- [ ] create Task component 
   - [ ] props : { task }
- [ ] render Error component in case of an error
- [ ] render Loading component when data is loading

**Comment by willywdev** [comment]
Looks really good!
How does the Loading and Error Messages look like?
