### ISSUE TITLE
UserStorie 6

### ISSUE THREAD

**Issue by RolandJBaron** [UmaySoyluer/capstone-project#17]
## Value proposition

As a team member 
I want to get a clear information on a page 
when there is an error or 
when the site is loading 
so i can see meaningful things while waiting

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/142206832/809787a5-a4d0-4399-962c-bc9ae85326a6)

## Acceptance criteria
- [ ] when a occurrence happen I see an Error page with
- [ ] a home button linking to the home page
- [ ] a message with error status 
- [ ] a picture (animal?)
- [ ] while Loading I see a Loading page with:
- [ ] a button linking to the home page
- [ ] a loading animation
- [ ] a text Loading...

## Tasks
- [ ] create a Error Component, which accepts message as props 
- [ ] Add a Home Button link from Buttons component
- [ ] Add an image
- [ ] Error Component renders an error message from props below the image
- [ ] create a Loading Component
- [ ] Add an animation to the loading page
- [ ] Add a text Loading... below, the animation
- [ ] render the page instead of simple Loading everywhere it needed
