### ISSUE TITLE
User Story 9 -  Task Detail

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#18]
## Value proposition
As a **team member**
I want **to see all details of a task with the description, a tag and a date of issue**

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/006e252b-8416-4739-800a-80c7a994c723)

## Acceptance criteria
- [ ] each Task on the Project Detail Page is clickable as a link and navigates to the corresponding Task Detail Page
- [ ] the Heading component is rendered at the top left corner of the Task Detail Page
- [ ] the Back link is displayed as an icon of a ‘left arrow‘ at the left top corner next to Heading , with clicking  user will be redirected to the Project Detail Page
- [ ] the following informations about the task are displayed:
   - [ ] title
   - [ ] description
   - [ ] tag (corresponding tag of the task is highlighted with color)
   - [ ] date of creation

## Tasks
- [ ] create [id] file in pages/ tasks
- [ ] create [id] file for dynamic routing in pages/ api/tasks
   - [ ] use router.query for find the tasks id
   - [ ] use GET method
   - [ ] implement error handling
- [ ] create a page TaskDetail component that renders
   - [ ] task.title
   - [ ] task.descripton
   - [ ] task.tag
   - [ ] task.createdAt
- [ ] TaskDetail props : {task}
- [ ] add an href attribute to the Back link to redirection to Project Detail Page

**Comment by MukaddesUzdoganlar** [comment]
Looks good to me!
