### ISSUE TITLE
Edit Task

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#19]
## Value proposition
As a team member 
I want to edit  a task 
in order to keep my project updated.

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/694cf0fc-a0d2-4d1c-b9c1-29c8a85bc6dc)

## Acceptance criteria
- [ ]the Edit Button is displayed at the top right corner of the Task Detail Page as an icon

- [ ]clicking the Edit Button navigates to the page with form with the previous information of the corresponding task are displayed in the input fields, and the user can edit all of these informations

- [ ]the Heading is displayed at the top of the page as “Edit Task”

- [ ]the Submit Button is displayed at the bottom of the page and labeled "submit"

- [ ]the Cancel Link is displayed at the bottom of the page and labeled "cancel"

- [ ]after submitting the form , user will be navigated back to the Project Detail Page  and the updated task will be displayed in current tasks list

- [ ]clicking Cancel Link navigates back to the Task Detail Page 

## Tasks

- [ ] TaskForm props:
 - [ ] formName = “edit-task”
 - [ ] onSubmit
 - [ ] task

- [ ] create a handleSubmit function in form that
 - [ ] updates the selected task
 - [ ] updates the data on db
 - [ ] navigates the page back to project detail

- [ ] use PUT method in pages/api/tasks/[id] to update the values of a task
implement error handling
 
- [ ] render the Submit Button to save updated form

- [ ] render the Cancel link  and add href attribute to redirect back to the Project Detail Page

**Comment by julialoeschel** [comment]
awesome.
