### ISSUE TITLE
User Story 10 -  Delete Task

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#20]
## Value proposition
As a **team member**
I want to **delete a task**
In order to **keep task list updated**
## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/e65298af-72a5-4e9f-9882-7391d2f5d5c8)

## Acceptance criteria
- [ ] the Delete Button is displayed at the top right corner of the Task Detail Page as an icon
- [ ] clicking the Delete Button deletes the task and redirects to the Project Detail Page 

## Tasks
- [ ] add DELETE method in pages/api/tasks/[id] to remove the task 
- [ ] implement error handling with try/catch
- [ ] add DeleteButton component with a delete icon and a prop onClick
- [ ] render the DeleteButton on the TaskDetail.js and implement handleDelete function that:
   - [ ] deletes the task 
   - [ ] redirects page to the Project Detail Page

**Comment by julialoeschel** [comment]
great job!
