### ISSUE TITLE
user Story 8 - Create Task

### ISSUE THREAD

**Issue by RolandJBaron** [UmaySoyluer/capstone-project#21]
## Value proposition
As a team member I want to
add a task to a project
to see what I have to do

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/142206832/829f638e-2333-4c61-b959-e8f9a2541cda)

## Acceptance criteria
- [ ] the add-task-button is displayed on the project detail page below the project description, which navigates to a form to create a task
- [ ] the Task Form has
   - [ ] input - name - required
   - [ ] input - description - required
   - [ ] 5 div for each tag - backlog , sprint backlog, in progress , quality assurance, done 
   - [ ] submit button
   - [ ] cancel button as Link
- [ ] after submitting the form , the new task will appended to the task list and user will be navigated back to the Project Detail Page
- [ ] Clicking cancel-button closes the form without submitting and navigates back to Project Detail Page

## Tasks
- [ ] create a new POST method in /pages/api/index to save a new task in the db
- [ ] implement error handling with try catch
- [ ] create a page NewTask in pages/tasks
- [ ] create a TaskForm in components/ with two input fields , a tag selection , a submit button and a cancel button
- [ ] create a Task in components/ with a prop Title. It renders a small card with a title
- [ ]  TaskForm props:
   - [ ] formName = “create task”
   - [ ] onSubmit
- [ ] create a state for tags in TaskForm
- [ ] render the TaskForm component in pages/projects/new-task.js
- [ ] implement a handleSubmit function that
   - [ ] creates a new task 
   - [ ] updates the data on db
   - [ ] redirect back to Project Detail Page
- [ ] add href to Cancel link to redirect to Project Detail Page

**Comment by julialoeschel** [comment]
Hey, 
in the ACs we dont need to use dev language (since the target group are not devs). I suggest to rephrase these infoemations: 
 - input - name - required
- input - description - required
- 5 div for each tag - backlog , sprint backlog, in progress , quality assurance, done

and also, the tags, shall they be check-boxes? (if yes, please state this in Tasks) 

great job 🦆
