### ISSUE TITLE
User Story 12 - Filter Task

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#22]
## Value proposition

As a team member 
I want to filter the tasks by tag 
In order to get the current task list

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/8c25d009-00a5-4ae3-8721-21dd186c76d9)

## Acceptance criteria

- [ ] clicking on the list title opens a dropdown menu  where the user can select another filtered view (for example: “In Progress”)

- [ ] the list will then only show the tasks with the selected filter tag

## Tasks

- [ ] element with the <option>:
   - [ ] Backlog
   - [ ] Sprint Backlog
   - [ ] In Progress
   - [ ] Code Review
   - [ ] Quality Assurance
   - [ ] Done

- [ ] the <option> element should listen to an onChange event
 
- [ ] create the function handleChange which receives the event.target.value and filters the displayed tasks depending on the value

**Comment by willywdev** [comment]
Looks very promising!

I suggest to describe how the empty Options-Page looks like. For example if there is nothing on "Sprint Backlog". Is it gonna stay empty or are you showing something e.g. "Nothing here."

**Comment by julialoeschel** [comment]
amazing!
