### ISSUE TITLE
User Story 1 - Project Overview

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#3]
## Value proposition
As a **team member**
I want to **overview all projects**
In order to **i can see projects to work on**
## Description
The page that includes overviews of all projects

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/1470eb48-e7a8-41bf-a5fd-74cfeeee3d17)

## Acceptance criteria

- [ ] on the home page a list of all current projects is displayed
- [ ] page title is displayed
- [ ] each project’s title is displayed 
- [ ] the project overview is vertically scrollable
- [ ] if there is an issue loading the data, an error message is displayed

## Tasks

- [ ] create a branch `feature/projects-overview`
- [ ] create a repo structure (all folders)
- [ ] create `ProjectsOverview` in `pages/projects/index.js`
- [ ] create the component `ProjectList`
- [ ] create the component `Project` 
- [ ] create the component `Heading`
- [ ] Project props: `project`
- [ ] Project should render:
   - [ ] Title in `Heading` component
- [ ] ProjectList should render:
   - [ ] Project component for each project in the array (map)
- [ ] create an Error component
- [ ] fetch a list of current projects from the api in `ProjectList`
- [ ] in error case conditional rendering on `ProjectList` show `Error`
- [ ] write backend function read in `pages/api/projects/index.js`
- [ ] create a database with one object by template (it will be a default project)
- [ ] create a model for a project in `db/models/Project`

**Comment by abaibik** [comment]
![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/042dc798-1ca1-439f-919f-6f9b21091268)

**Comment by FelineHuhn** [comment]
Hey team, good job so far. :) I have some fundamental suggestions for this and also future user stories: Have a look at the user story template, you got from us, to adjust your user stories layouts (for a consist and easy understanding user story): 

- It would look more consist, when the word user in the title has also a big capital letter "User"

- The value proposition should have another format like: 
![Image](https://github.com/UmaySoyluer/capstone-project/assets/112863528/e0f3d372-5939-43c8-bad6-333cf168bce9)


- The wireframe should not be in the comments section below your user story, but inside the Description part

- The Acceptance Criteria and the Tasks should have checkboxes instead of bullet points 

- You have also the option to make sub-checkboxes as a child from a checkbox, when you indent a little to the right by pressing the space key like two-three times

**Comment by FelineHuhn** [comment]
Great progress team! The improved layout is good now. I have now some more suggestions for the content of the user story. 

**Value Proposition:** 
- a little typo is here, it should read as "overview" and not "overblick", or?  
- the value proposition could still be formulated a bit more purposefully without repeating (oversee and overview for benefit and purpose is a bit doubled, or?) - if you want, you are welcome to take my suggestion (or parts of it) from my comment above. 

**Description:** 
- i love the Wireframe! 
- Since in the acceptance criteria you mention, that these are the current projects, the headline could also be "Current Projects" or even more simple just "Projects"... but that's of course a matter of taste. 
- the card border is not just a border but an image of the project, or? You maybe could show it in a simple way, that the image is the background of the project card (or i totally misunderstood the location of the image?)
- when you have a loading / error screen, like you mention it in the acceptance criteria, you should also make a wireframe for these cases

**Acceptance criteria:** 
- the first two lines should be in one
- "each project’s image is displayed" and "each project’s title is displayed" could be sub-checkboxes from the checkbox above for better readabilty (matter of taste - you can write it like this too of course)
- "the create button is displayed" should be removed, since you don't have it in this feature
- you should think about what kind of image the project's image is and mention it here, is it a placeholder image, so that every project has the same image? I think an image upload via create form in the create user story is not planned in the first sprint, or? SO think about the image... do you want one already? 

**Tasks:**
- the lines have so much space between, can you change this like you did it in the acceptance criteria section? 
- you maybe should choose a more meaningful branchname like `feature/projects-overview`
- What do you mean with "repo structure"? 
- you can formate a component e.g. ProjectList as `ProjectList ` when you wrap it in back ticks, it supports better readability of your user story
- you better could choose a project/folder structure, that the bootcamp was teaching (have a look in the [self-directed-learning ](https://github.com/neuefische/cgn-web-23-2/blob/main/sessions/self-directed-learning-week-7/challenges-self-directed-learning-week-7.md) for a common folder structure)
- i think the `ProjectsList` should be implement on the `index.js`, since this is the "homepage" like you mentioned in the acceptance criteria and is the starting point of the app for now, or? 
- For all other tasks: you could be in general a bit more specific in your tasks and also work more with sub-tasks
   - example for more specifictiy: instead of "create ProjectsOverview in pages/projects/index.js" mention, that it is a page (even, when you show the path) or instead of "Project props: project" you should describe it more like "the component `Project` receives the prop `project`
   - example for sub tasks: (I take the not improved tasks for this example) "Project props: project" and " Project should render: ... ) could be sub tasks from the task above "create the component Project in features/projects/Project.js"
