### ISSUE TITLE
User Story 14 - Dark Theme

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#35]
## Value proposition

As a team member 
I want to be able to customize the theme of the app 
in order to it can look better to me.

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/53e891d0-1c33-4baf-9ab6-9f3e75169813)

## Acceptance criteria

- [ ] The Toggle Button is displayed at the top right corner of the Projects Overview Page as a slider
- [ ] Clicking Toggle Button switches between the light mode and dark mode on every pages

## Tasks
- [ ] install next-themes
- [ ] in _app.js import Theme Provider from next-themes
- [ ] place the imported Theme Provider component inside App function
- [ ] import useTheme in Projects Overview Page and implement to set theme 
- [ ] create StyledToggleButton in Buttons.js and import it in Projects Overview Page
- [ ] implement onChange function to set theme
