### ISSUE TITLE
User Story 15 - Confirm Delete

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#38]
## Value proposition

As a team member 
I want to have a confirm-delete dialog 
in order to i can avoid accidental deletion of critical data.

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/72cf6632-f454-4960-bf5d-f909ba6415f1)

## Acceptance criteria

- [ ] when user attempts to delete an item ( a project or a task ), a confirm delete pop-up should be displayed.
- [ ] the pop-up should contain a clear message, with title and text ; such as "Are you sure you? Do you really want to delete this item?" and two action buttons: "Cancel" and "Delete."
- [ ] Clicking the "Cancel" button should close the pop-up, cancel the deletion action, and return the user to the previous state
- [ ] Clicking the "Delete" button should delete the item and close the pop-up.
- [ ] there should be no accidental deletions once this feature is implemented.

## Tasks

- [ ] install the library for pop-up 
- [ ] implement handleDelete functions to display the pop-up when the delete action is initiated
- [ ] modify the delete API endpoint to handle confirmation, ensuring that data is only deleted when the user confirms
