### ISSUE TITLE
User Story 16 Unit Tests Environment

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#39]
## Value proposition
As a team member
I want to have Unit-tests in code of App that I use
In order to be sure that everything works well

## Description
- Unit-Testing for our App

## Acceptance criteria

- [ ] Unit Tests Environment is setted up
- [ ] Unit Tests for index.js page don't fall

## Tasks
- [ ] Install and set up React Testing Library 
- [ ] Install and set up Mock Service Worker
- [ ] Install and set up isomorphic-fetch module 
- [ ] Write Unit-tests for items that appear on index.js page (a heading, a list of projects)
