### ISSUE TITLE
User Story 17 - Project Detail Desktop

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#42]
## Value proposition

As a team member,
I want to view and manage project details on the desktop version of the app,
So that I can efficiently organize and update the projects.

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/e4c45b31-b6c0-40a5-bf36-ba214f253516)

## Acceptance criteria

- [ ] the Project Detail Page in the desktop version of the application,  all the task lists for the selected project are displayed on the screen. These task lists should be vertically scrollable to accommodate all tasks.
- [ ] Each task list should show relevant information such as the task name
clicking on the "Add Task" button to open a pop-up form for creating a new task. 
- [ ] This form should include fields for task name and task description. Upon submission, the new task should be added to the respective task list.
- [ ] clicking on the "Edit Project" button to open a pop-up form for editing project details. This form should allows to modify the project name, description, and other relevant project information. Upon submission, the project details should be updated.
- [ ] the pop-up forms should have a cancel button, that allows to exit the form without making any changes.
clicking the Submit button should be save and reflect the changes on the Project Detail Page

## Tasks

- [ ] the Project Detail Page on Desktop version:
   - [ ] implement the layout for the Project Detail Page.
   - [ ] display all task lists vertically scrollable
- [ ] the "Add Task" Button:

   - [ ] Implement the functionality to open the task creation pop-up form when the button is clicked.
- [ ] the “Edit Project” Button:
   - [ ] Implement the functionality to open the project editing pop-up form when the button is clicked.
- [ ] Design and implement the task creation pop-up form with fields for task name and task description.
   - [ ] Add a "Submit" button to save the new task.
   - [ ] Add a "Cancel" button to exit the form without saving.
- [ ] Design and implement the project editing pop-up form with fields for project name, description, and other relevant project information.
   - [ ] Add a "Save" button to save the edited project details.
   - [ ] Add a "Cancel" button to exit the form without saving.
- [ ] changes made within the pop-up forms are reflected on the Project Detail Page without requiring a page refresh.

**Comment by julialoeschel** [comment]
great work there!
