### ISSUE TITLE
User Story 18 - Priority Tags

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#43]
## Value proposition
As a team member I want to set and see the priority of a task, so that I understand what is more important to implement
## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/35653742-3d84-4ddc-92c1-2821e590302b)

## Acceptance criteria

- [ ] each Task has a “priority” property
- [ ] user should be able to create a new task and assign a priority tag (High, Neutral, Low) to it during task creation.
- [ ] The priority tag should be clearly visible in the task details.
- [ ] user should be able to edit the priority tag of an existing task.
- [ ] When editing a task, I can change the priority tag to High, Medium, or Low.

## Tasks
- [ ] add radio-buttons on FormTask: high, neutral , 
- [ ] implement a function, that set a task a priority value 
- [ ] TaskDetail component renders also task.priority
- [ ]  Add a priopity property to the Task model , priority: []
- [ ]  Add a priority property to the Tasks collection in database
