### ISSUE TITLE
User Story 22 - Profile Page

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#46]
## Value proposition

As a team member 
I want to have a profile page 
in order to access and manage my user profile information

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/35aa97e3-f84f-4f9b-a17c-75c39bad8f41)

## Acceptance criteria

- [ ] When user log in to the project management tool, user should be able to access the user profile information from the main navigation or profile icon.
- [ ] Clicking on the user profile should display a dedicated page where user can view my information.
- [ ] The displayed user profile information should include full name, email address, profile picture, job and department
- [ ] While viewing the user profile, user should have a direct link to navigate to the project board
- [ ] Clicking on the "Go to My Project Board" link should instantly take user to the project workspace.
- [ ] There should be a "Log Out" icon at the top right corner 
- [ ] Clicking "Log Out" should securely log user out of the project management tool, ensuring that the session is terminated.

## Tasks

- [ ] Create the folder pages/profile to handle the profile page.
- [ ] Secure the profile page to ensure only authenticated users can access it.
- [ ] Fetch the user's profile data from the database. This include details like name, email, profile picture, and other relevant information.
- [ ] Populate the profile page with the user's information, which is fetched from the data source.
- [ ] Display the user's name, email, profile picture, and other relevant data
- [ ] Provide the way for the user to log out from their profile page. This involves making a logout request to the authentication service and clearing the user's session.
