### ISSUE TITLE
User Story 22  - Home Page

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#47]
## Value proposition

As a **team member**
I want to **see a home page**
In order to **have the whole information about the application**

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/98355fae-4b39-44a2-bbca-49f1c7fbce16)

## Acceptance criteria
- [ ] on a Home page I see 2 scopes of text with 2 call-to-action buttons
- [ ] the Home link of Header redirect to this page
- [ ] call-to-action buttons redirect to the Projects Overview

## Tasks
- [ ] push the content of ProjectsOverview to pages/projects/ProjectsOverview.js
- [ ] generate a landing page-like text with ChatGPT
- [ ] create a CallToActionButton in components
- [ ] add this content to pages/projects/index.js
- [ ] add photos of team members to the 2 scope (created by)
- [ ] by CallToActionButton click:
   - [ ] redirect to the Projects Overview
