### ISSUE TITLE
User Story 21 - Profile Edit & Delete

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#48]
## Value proposition

As a team member , 
I want to make necessary edits and delete my profile if needed 
in order to have a updated personal informations.

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/2d1392d5-a46c-4c02-9687-4a512e7b54e0)

## Acceptance criteria

- [ ] the edit profile button is displayed next to the “Go to my board” button in profile page
- [ ] by clicking the "Edit Profile" button, the user should be able to modify all relevant informations
- [ ] by clicking the "Edit Profile" button , a pop-up form is displayed which has corresponding inputs of user’s data
- [ ] Submit Button , Cancel Button and also Delete Button are displayed in form
- [ ] user can change and update informations with submitting
- [ ] user can go back with cancelling
- [ ] Clicking Delete Button deletes the profile and navigates back to landing page

## Tasks

- [ ] create the Edit profile Button
- [ ] handle form submission and update the user's information in the database.
- [ ] create the Delete profile button
- [ ] implement handleDelete function to remove user’s data from the db.
- [ ] use Cancel Link to navigate back to profile page
