### ISSUE TITLE
user Story: 19 -  Sign In with Githut

### ISSUE THREAD

**Issue by RolandJBaron** [UmaySoyluer/capstone-project#50]
## Value proposition
As a user
I want to log into my account using my Github Profile
In order to see the allocated assignments
## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/142206832/2bbe8030-a31a-4e3b-a11d-b4d8a37e5f7e)

## Acceptance criteria
- [ ] An account Icon is displayed on the Home page and redirect to the Github Login form
- [ ] Login form is displayed:
   - [ ]  A login with github” button with the github icon on it
- [ ] By button click
   - [ ] redirect to github auth. page
   - [ ] when ok
   - [ ] new user is created in database
   - [ ] redirect to the personal page
- [ ] a back button that directs back to the home screen

## Tasks
- [ ] create a O auth link for Github so users can sign in
- [ ] create a mongoDB database connection
- [ ] the users login credentials on a database for the future
- [ ] create a back button to navigate to the home screen
