### ISSUE TITLE
User Story 23 - Navigation Bar

### ISSUE THREAD

**Issue by UmaySoyluer** [UmaySoyluer/capstone-project#52]
## Value proposition
As a team member, I want to have a user-friendly and efficient navigation bar  
in order to navigate the app smoothly and access the key functionalities with ease.
## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/120322691/18d8f9f0-2734-4792-8469-bf9499267fde)

## Acceptance criteria

- [ ] identifiable navigation bar at the bottom of the page (mobile version) at the top of the page (desktop version)
- [ ] In the navigation bar,  "Profile" icon ,  “Dark Mode” icon , “Home” icon and also “Projects” icon are displayed
- [ ] The navigation icons should have clear and intuitive visual cues to indicate their functions, such as icons representing a user for "Profile," a moon or sun for "Dark Mode," a house for "Home," and a project-related icon for "Projects."
- [ ] clicking each icon navigates user to the corresponding page

## Tasks

- [ ] - [ ] create the navigation component for mobile and desktop version
- [ ] import and add the relative icons to the navigation bar
- [ ] implement navigation href functionality to each icon
