### ISSUE TITLE
User Story 24  - Log In / Sign Up

### ISSUE THREAD

**Issue by RolandJBaron** [UmaySoyluer/capstone-project#54]
## Value proposition
As a team member 
I want to create a account.
In order to log into my account in the future.

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/142206832/f63b861f-3d65-4603-a749-27cab049f5bd)

## Acceptance criteria
- [ ] Sign Up:
   - [ ] by button onClick
   - [ ] Complete the form
      - [ ] unique Username -"warning username already exists"
      - [ ] email address
      - [ ] password
- [ ] by submit
   - [ ] a new user is created in database
   - [ ] pop-up success “account created”
   - [ ] redirect to my personal page

- [ ] log-in:
   - [ ] by button onClick: 
   - [ ] user fill in his/her the log in credentials
- [ ] by submit
   - [ ]  prove the information in the database
   - [ ] pop-up success “welcome message”
   - [ ] redirect to my personal page
- [ ]   add a home button to redirect back to the home page
 
## Tasks
- [ ] create a login and sign up page
- [ ] create a input field to enter username
- [ ] create another input field to enter Password
- [ ] create a Log in button
- [ ] create a signup button
- [ ] create a sign up page
- [ ] save the users login credentials on a database for the future.
- [ ] secure the users passwords with password hashing
- [ ] create a cancel button to empty the input fields

**Comment by julialoeschel** [comment]
Hey there, 
the AC and the tasks are a little differing. do you need username AND Emanil Adress? or just one of them? and is the scribble correct? (no emialadress)

Try to keep the ACs without any developer language, to target the non dev colleques in your team. 
-> " by button onClick" -> -> "by clicking sign Up button" and so on.

and is the sign up view different from the log in view? if yes, pleas scribble all views. 

all in all I think we should slim out the Story. 
could we make it 2 - 3 stories? 

1: login with password (have dummidata in the DB, check if user exists and if password is correct, log user in or indicate that the password is incorrect)
2: log a new user in (create new user, check if user exists, log user in) 
3: get all the pop up messages in


what do you think about that?
