### ISSUE TITLE
user Story 25  - Sign Up

### ISSUE THREAD

**Issue by RolandJBaron** [UmaySoyluer/capstone-project#56]
## Value proposition
As a team member
I want to create a account.
In order to log into my account in the future

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/142206832/c62237d7-d271-4270-9066-19341c368253)

## Acceptance criteria
- [ ] Sign Up:
   - [ ] by clicking sign Up button
   - [ ] Complete the form
      - [ ] Create your unique Username -"warning username already exists"
      - [ ] enter your email address
      - [ ] set your password
- [ ] by submit
   - [ ] a new user is created in database
   - [ ] pop-up success “account created”
   - [ ] redirect to my personal page
- [ ] if username already exists pop up message " Username already exists"
- [ ] a home button to take the user back on the homepage

## Tasks
- [ ] create a sign up page
   - [ ] create a input field to enter username
   - [ ] create a input field to enter email address
   - [ ] create another input field to enter Password
- [ ] create a sign up button
- [ ] save the users login credentials on a database for the future.
- [ ] secure the users passwords with password hashing
- [ ] create a cancel button to empty the input fields
- [ ] add a back home button
