### ISSUE TITLE
User Story 4 - Delete Project

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#6]
## Value proposition

As a **team member**
I want to **delete a project**
In order to **make room when it is no longer needed**

## Description

A button "delete" on a project board

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/ffc9d3e0-43ad-40b1-b84c-f35c02deef9f)

## Acceptance criteria
- [ ] the delete-button is displayed in project detail page
- [ ] clicking the delete-button removes the project from the list and reloads the page so the changes apply immediately

## Tasks
- [ ] create the DeleteButton as a variant of the Button component
- [ ] render the DeleteButton component as a child of the Heading component on the ProjectDetail page
- [ ] implement a handleDelete function that
   - [ ] removes the selected project 
   - [ ] take the query parameter id from next/router
   - [ ] use the id to find the project to delete

**Comment by julialoeschel** [comment]
Hey There. 

Good job!
I found some things to consider: 
- in your scribble, the delete button looks more like a closing button. Try to find a more "delete-like-looking" symbol or svg.
- what happens to the user after he/she deleted the item? I guess a redirect to the overview? this shall be found in the AC. 

I hope that helps a bit
keep up the good work. 
🦆

**Comment by FelineHuhn** [comment]
LGTM now :)

**Comment by miriam-ertl** [comment]
QA: LGTM.
