### ISSUE TITLE
User Story 26- DND

### ISSUE THREAD

**Issue by TheRealChio** [UmaySoyluer/capstone-project#61]
## Value proposition
As a team member
I want to be able to move tasks between lists via drag and drop.
In order to have a better app experience

## Description

The user will be able to move the tasks between lists via drag and drop.
When the user selects a task by holding down the left mouse button on desktop
and the finger on mobile the task will become dragable. Now the user can move the task
between the lists and drop it inside the new list.

## Acceptance criteria
- [ ] Tasks need to be dragable between lists
- [ ] Lists need to be a dropable container

## Tasks
- [ ] Use react-beautiful-dnd for drag and drop and inplement it inside the TaskList component
