### ISSUE TITLE
User Story 26 - Tests and Bug fixing

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#63]
## Value proposition
As a **team member**
I want to **delete columns and test the authentication functionality**
In order to **be sure, that the application works well**

## Description
- There aren't authentication tests
- Delete button by columns doesn't works correctly (deletes all the columns)
- All tests are run only manually
- Landing page text on a tablet is too short
- There are testing library warnings by deploying
 
## Acceptance criteria
- [ ] There are no warnings by deploying 
- [ ] All tests are run by deploying by themselves
- [ ] Delete button by columns works
- [ ] Landing page text on a tablet looks good
- [ ] There are authentication tests

## Tasks
- [ ] Add a file .github/workflows/build-and-test.yml to set the tests by deploying 
- [ ] Separate actions to check the authentication into a custom hook
- [ ] Fix bug in TaskList (delete button doesn't work)
- [ ] Fix text width on index.js (add clamp)
- [ ] Set packages of Testing library
