### ISSUE TITLE
User Story 5 - Edit Project

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#7]
## Value proposition

As a **team member**
I want to **edit the project**
In order to **be able to react to changes for a project"**

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/124400237/5a3c671e-3d83-4c0b-a8d4-2726d6ffb04f)

![Image](https://github.com/UmaySoyluer/capstone-project/assets/124400237/4a7ef4dc-f90f-476c-a771-4a6e59f9ba66)

## Acceptance criteria

- [ ] the edit-button is located at the top corner of projects overview page as an edit icon
- [ ] clicking the edit-button navigates to the page with form with the previous information of the corresponding project are displayed in the input fields, and the user can edit all of these infos
- [ ] the headline is displayed at the top of the page
- [ ] the submit button is displayed at the bottom of the page and labeled "cancel"
- [ ] the cancel-button is displayed at the bottom of the page and labeled "edit project"
- [ ] after submitting the form , user will be navigated back to the projects overview page and the updated project will be displayed in current projects list
- [ ] clicking cancel button navigates back to the project detail page
 

## Tasks

- [ ] create the EditButton as a variant of the Button component
- [ ] render the EditButton component next to the Heading component and delete button
- [ ] render the Form component in pages/projects/[id]/edit-project.js
- [ ] implement a handleSubmit function that 
   - [ ] updates the selected project 
   - [ ] updates the data on mongodb
   - [ ] navigates the page back to projects overview

- [ ] Form props: 
   - [ ] formName = “edit-project”
   - [ ] onSubmit
   - [ ] project

- [ ] take the query parameter id from next/router
- [ ] use the id to find the project to update
