### ISSUE TITLE
User Story 6 - Navigation

### ISSUE THREAD

**Issue by abaibik** [UmaySoyluer/capstone-project#8]
## Value proposition

As a **team member**
I want to **easily switch between projects overview and project detail**
In order to **navigate the app**

## Description

![Image](https://github.com/UmaySoyluer/capstone-project/assets/78874362/51f20a43-dc00-43a6-a401-baa2a8c9cbe8)

## Acceptance criteria
- [ ] a navigation link labeled `<-`  is displayed on the top left corner of project detail page
- [ ] clicking the navigation link brings the user back to projects overview page

## Tasks
- [ ] create the component `Navigation` inside `ui/Navigation.js`
- [ ] the `Navigation` should be a Link that navigates the user back to `/projects`
- [ ] render `Navigation` component at the top of the project detail page

**Comment by FelineHuhn** [comment]
Hey ducks :) This user story should not be an own feature but a part of the details page feature, because when you implement the details feature without a back link, the user cannot go back and the functionality of the whole app is kind of broken, or?

**Comment by miriam-ertl** [comment]
Thank you for letting me read the US. It Looks Good To Me – LGTM

**Comment by FelineHuhn** [comment]
Please consider my last comment and merge this back link into your details feature. :)
